### ISSUE TITLE
[ feat ] todo-list 만들고 localstorage에 데이터 저장 기능 개발

### ISSUE THREAD

**Issue by meeyoungchoi-front-dev** [meeyoungchoi-front-dev/JavaScript-UI-Component-Projects#15]
- [x] todo 작성 기능 개발
- [x] todo 목록 조회 기능 개발
- [x] todo 완료시 체크 기능 개발
- [x] todo list 각 항목 삭제 기능 개발
- [x] local storage에 todo 항목 저장 기능 개발 (CRD) => 브라우저 새로고침 또는 브라우저 껐다켰을때 보여질 수 있도록 하기 위함

기능 상세 설명
- input-box 요소가 빈 값인경우 alert을 띄우고 빈값이 아닌경우 li 요소를 생성하여 inputBox.value 값을 li.innerHTML에 저장한다
- listContainer에 li를 누적시키기위해 append 함수를 호출한다
- li 요소 삭제 기능을 위해 span 요소를 추가한다
- listContainer의 각 아이템을 클릭할때 마다 tagName 값에 따라 분기 처리를 진행한다
- 각 분기처리 결과를 로컬스토리지에 저장한다
- 브라우저를 새로고침하거나 껐다 켜도 localstorage에 list가 저장되 있기 때문에 상태가 유지된다

스크린샷
![image](https://github.com/user-attachments/assets/cddc3abf-2e25-4e98-b4d0-f5715778a8a2)
![image](https://github.com/user-attachments/assets/e2a973c0-f1ca-4136-86b6-583a12cedab3)
![image](https://github.com/user-attachments/assets/bf936173-f38e-4144-b5ad-15cbb9186c21)
![image](https://github.com/user-attachments/assets/f1a4ea76-7ab3-4734-9614-24f3ef4bc6ab)
